### ISSUE TITLE
Missing newline when evaluate on last line

### ISSUE THREAD

**Issue by t4ccer** [haskell/haskell-language-server#1213]
Using `Evaluate` on
```haskell
-- >>> take 5 [0..]
```
produces
```haskell
-- >>> take 5 [0..]-- [0,1,2,3,4]
<here is newline>
```
instead of
```haskell
-- >>> take 5 [0..]
-- [0,1,2,3,4]
```
when `>>> take 5 [0..]` is on the last line of file. I believe that appending newline character on beginning of `Evaluate`'s output instead of at the and will solve the issue.

**Comment by expipiplus1** [comment]
@tittoassini is perhaps a better person to look at this.

**Comment by tittoassini** [comment]
The problem is that the Eval plugin will instruct the client to add the result in the line after the test. 

However, if the line does not exist, the client will attach it to the last line instead.

For File:
0: module TLastLine where
1:
2:-- >>> take 5 [1..]-- [1,2,3,4,5]

We say "put the result on line 3":

{"jsonrpc":"2.0","params":{"edit":{"changes":{"file:///Users/titto/workspace/haskell-language-server/plugins/hls-eval-plugin/test/testdata/TLastLine.hs":[{"range":{"start":{"line":3,"character":0},"end":{"line":3,"character":0}},"newText":"-- [1,2,3,4,5]\n"}]}}},"method":"workspace/applyEdit","id":14}

Clients says: "ok, there is no line 3 so it goes at the end of line 2!":

{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///Users/titto/workspace/haskell-language-server/plugins/hls-eval-plugin/test/testdata/TLastLine.hs","version":20},"contentChanges":[{"range":{"start":{"line":2,"character":19},"end":{"line":2,"character":19}},"rangeLength":0,"text":"-- [1,2,3,4,5]\n"}]}}
