### ISSUE TITLE
suggestImportDisambiguation does not interact well with DuplicateRecordFields

### ISSUE THREAD

**Issue by berberman** [haskell/haskell-language-server#1457]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.0.0.0 (GHC: 8.10.3) (PATH: /home/berberman/.cabal/store/ghc-8.10.3/haskell-language-server-1.0.0.0-c7859e8f45ef6bd2fac7adc65982f4e497ee3c40299bcc89c5915aaa0534ebc3/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          Not found
ghc:            8.10.3
```
Which lsp-client do you use:
vscode

### Expected behaviour

There should be no suggestion, because the ambiguity comes from DuplicateRecordFields, rather than imports.

### Actual behaviour

![2021](https://user-images.githubusercontent.com/26041945/109413749-0221a680-79ea-11eb-8e3a-096c79260fb2.png)

These code actions are meaningless in this case.

**Comment by adamgundry** [comment]
If you want to be really clever, in this situation you could suggest adding `import qualified A as RecA (RecA(..)` and replace with `RecA.foo`. But perhaps that's a bit complex to figure out.

**Comment by July541** [comment]
For the original issue, I just wondering if we have another file B.hs simultaneously:
``` haskell
module B where

newtype RecC = RecC { foo :: Int }

```
What suggestions should ghcide gives? Maybe `Replace with qualified: B.foo` (cause hiding can not work for duplicated records) is not a bad choice.

@adamgundry 's idea seems an appropriate solution, which can eliminate the worry above, but it may make the original function `suggestImportDisambiguation` too huge to maintain, can anyone give some advice? 

----

Meanwhile, we must notice that if we choose to keep the `foo` from `B` and hide others in the current version, it will print double `foo` in `A`.

![image](https://user-images.githubusercontent.com/16057632/113155124-4adbb200-926b-11eb-8728-95949b332da8.png)

If we choose `foo` from `A` and hide others, it will add `hiding (foo)` to the two imports simultaneously, it will use `foo` in `RecB` due to `RecB` is at the bottom of the `RecA`.

![image](https://user-images.githubusercontent.com/16057632/113155809-01d82d80-926c-11eb-8f65-fd0868291434.png)

Our fix should consider these two situations. Please point out if I missed any other conditions.

**Comment by July541** [comment]
@berberman I am trying to fix this issue by just remove all ambiguities that are from the same module, does it make sense?

**Comment by berberman** [comment]
@July541 Nice, what will it look like? Could you give an example?

**Comment by July541** [comment]
@berberman Here are two samples:
1. With the same records name in exactly one module, we will ignore all the ambiguities due to they are not caused by ambiguity imports.
![image](https://user-images.githubusercontent.com/16057632/113394156-52fe3380-93ca-11eb-8b4e-c5280465ab14.png)


2. For the mixture of real ambiguity records and `DuplicateRecordFields` caused ambiguity, we only keep the ambiguity one from files without `DuplicateRecordFields` extension as suggestions and drop others.
![image](https://user-images.githubusercontent.com/16057632/113394217-6a3d2100-93ca-11eb-9701-9451bfabe23f.png)

**Comment by berberman** [comment]
Looks great, thanks!

**Comment by July541** [comment]
@berberman Can you point me out where I can include some tests? I am not sure about how to integrate with a test.

**Comment by berberman** [comment]
@July541 You could find related tests here:
https://github.com/haskell/haskell-language-server/blob/3e3d782cb88db41fce5c3994d2f131a86445e059/ghcide/test/exe/Main.hs#L1592
