### ISSUE TITLE
Wingman will unify types that don't share a context

### ISSUE THREAD

**Issue by isovector** [haskell/haskell-language-server#1548]
```haskell
{-# LANGUAGE RankNTypes #-}

blah :: (forall x. Show x => x -> String) -> a -> String
blah f = _
```

Running `auto` at the hole produces an extract `f`, which doesn't match since we don't have a `Show a`  in scope.

**Comment by Jashweii** [comment]
I was looking at this briefly to see if I could find a cause and is the unify in assume and apply actually doing full unification rather than subsumption?
For example ``forall a . Ord a => a -> a`` does not unify with ``Int -> Int`` but it does subsume it, plus this way you aren't accidentally changing the goal by unifying it. The difference is the types don't have to match exactly - you can provide an expression with a *more* general type. I don't know if this actually causes any issues or not. I think GHC provides this as ``tcMatchTy`` (very brief look), though I am not sure if it does exactly this.

This has changed somewhat however with simplified subsumption in GHC 9, and I'm not too familiar with the changes (it's probably worth asking someone who is).  It's entirely possible with simplified subsumption that none of this is necessary and it's ok to just instantiate the types of bound variables in the environment (which you already do).
https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0287-simplify-subsumption.rst
(The point of the proposal was in some cases with higher ranked types, the more extensive subsumption check can allow changing semantics)
