### ISSUE TITLE
Please mention haskell-language-server-bin as an alternative (or maybe primary) method of installation on Arch Linux

### ISSUE THREAD

**Issue by marcin-rzeznicki** [haskell/haskell-language-server#1634]
Wrt #1616 . I believe it'd be complementary to add [haskell-language-server-bin](https://aur.archlinux.org/packages/haskell-language-server-bin) as an alternative (and in many ways better) way of HLS installation on Arch. Community Haskell packages are constantly rebuilt because of dynamic linking, and there is no support for multiple GHC versions (due to dynamic linking) which will probably cause a lot of grief for unsuspecting users. In my eyes this makes it inferior to the aforementioned AUR package, thus I believe the AUR package should be promoted as a "main" way of getting HLS on Arch. But even not taking the above issues into consideration, I believe it deserves a mention as it has been around for a long time delivering updates in timely fashion.

**Comment by berberman** [comment]
Thanks for noting that, and PRs are welcome! As far as I know, almost nobody uses dynamically linked Haskell package on Arch Linux (other than package maintainers), because as you said, they are rebuilt frequently due to the unstable ABI and circular dependency involving test suites. The numerable advantages using these packages would be 1) You don't need to build extensive dependencies on your machine anymore (just like nix). 2) It takes up far less amount of disk space than the normal way does. However, the deficiency is still unneglected: you'll need rebuild all of your projects after rolling the system. Thus, I agree with you that Haskell packages from [community] are not good for developing, and we should prioritize the fully static version of HLS.

**Comment by marcin-rzeznicki** [comment]
Thanks! I'll try to cook something up this evening
