### ISSUE TITLE
case split on case of statement with no destructor cases declared

### ISSUE THREAD

**Issue by santiweight** [haskell/haskell-language-server#1716]
This isn't exactly Wingman, but I think @isovector is probably the man for the job (?) given what he's been working on...

```
case my expr of
```

In this case, we'll get some errors about allow "empty-case" and add "EmptyCase" etc. 

My suggestion: to add a code action that inserts empty case destructors:

```
case myMaybeValue of
```

becomes

```
case myMaybeValue of
   Nothing -> _
   Just val -> _
```

and now the same Wingman workflows are recovered.

**Comment by googleson78** [comment]
This is also useful when you want to split on the result of a function. Right now to do so I introduce a temp `let` bind
```haskell
let x = f y in _
```
 and then split on x, fixing up whatever is left afterwards.

**Comment by isovector** [comment]
Yeah, OK!

**Comment by isovector** [comment]
Actually, this is harder than it sounds. Without a hole, there's no way I know of to get the type of the scrutinee. If yall can come up with a way to either annotate or lookup that information, I'm happy to do the rest!

**Comment by isovector** [comment]
Just kidding. Apparently `exprType . dsExpr` does the right stuff.

**Comment by isovector** [comment]
This turns out to quite hard after all. I've managed to find empty cases in LSP and get the type of the scrutinee. But the Wingman internals really strongly believe they will only ever be called on a hole (and that you'll only ever destruct a variable). Oddly enough, the hardest part is just inserting the new matches into the `case`, since that stuff is locked away in a weird part of the AST that isn't particularly meaningful to operate on by itself.

There are a couple ways I can think of to force things through and get this working, but that seems like it's just taking on technical debt for no reason. But I'm hoping that if a little distance will elucidate the solution. If so, we can probably land this feature in the next week.

**Comment by isovector** [comment]
Pretty convincing proof of concept:

![test](https://user-images.githubusercontent.com/307223/114793408-2b4e8a00-9d3f-11eb-9128-32a4a9d72c20.gif)

**Comment by santiweight** [comment]
You're a beast @isovector thank you. If you link the WIP merge, I can take a look at the code (probably more for my benefit than yours).

**Comment by isovector** [comment]
@santiweight Thanks for the great suggestion. Code is over at #1721. I've got a spare evening, and hope to get it finished tonight.
