### ISSUE TITLE
Using "Find All References" on types returns function names

### ISSUE THREAD

**Issue by OliverMadine** [haskell/haskell-language-server#1719]
### Which OS do you use:
MacOS

### Which lsp-client do you use:

VS Code

### Steps to reproduce
do "Find All References" on "Foo" 

```Haskell 
data Foo = Val Int 

bar :: Foo -> Foo -> Bool 
bar (Val n) (Val m) = n + m > 5
```

### Actual behaviour
The function name ("bar") is highlighted as a reference. 

Is this the intended behaviour?

**Comment by jneira** [comment]
Mmm i would say that `bar` references the type in the signature so it would be correct, what other behaviour could have it?

**Comment by wz1000** [comment]
This is expected behavior. The idea is for "references" for a type to point you towards all bindings of values that include that type.

We could offer an option to disable this, or even limit the "depth" it considers for a type. For example, if `foo :: Int -> Bool -> X`, and `bar :: X`, `depth = 0` would only match `bar` while `depth <= 2` would match `foo` and `bar`.

**Comment by OliverMadine** [comment]
I think that this would be a great feature. Thanks for the explanation!

**Comment by OliverMadine** [comment]
> Mmm i would say that `bar` references the type in the signature so it would be correct, what other behaviour could have it?

Thanks, I understand now. I was initially expect behaviour similar to what wz100 described above.
