### ISSUE TITLE
Feature request: add missing cases

### ISSUE THREAD

**Issue by kcsongor** [haskell/haskell-language-server#1732]
Thanks for the great work on Wingman @isovector!
Something that would be quite useful is a code action to add missing cases to a function/case expression. The main use case is extending a data type with a new constructor. For example, given

```haskell
data Foo
 = A
 | B

split :: Foo -> Int
split A = 0
split B = 1
```

if I add a new constructor to `Foo`:

```haskell
data Foo
  = A
  | B
  | C
```

then a warning shows up about `split` not covering all the cases. It would be nice if a code action could add the missing case!

**Comment by isovector** [comment]
Going to untag this as "wingman" just in case someone else wants to implement it (I haven't yet started to look at any diagnostics,) but I'll think about how to make this happen if nobody else jumps on it.

**Comment by ndmitchell** [comment]
FWIW, in Rust, the fill missing cases is by far the most common action I use - it's become second nature. I think this probably ha a lot of value.

**Comment by isovector** [comment]
I guess this subsumes what I just implemented in #1721, so maybe it is in scope.

**Comment by jneira** [comment]
i think so, @kcsongor could you take a look to the solution in the pr to confirm it match your request? thanks!

**Comment by kcsongor** [comment]
I agree this feature subsumes #1721, which at the moment only supports filling in an empty case, whereas with this we could fill in case expressions that already have some cases (a more common scenario I think)

**Comment by isovector** [comment]
Dammit, you're right. I was so excited about #1721 too! I'll look into this tomorrow --- hopefully it's a pretty trivial patch on top.

**Comment by isovector** [comment]
So I did a little investigation here. The _right_ solution is to reuse GHC's exhaustiveness check, and then generate cases for everything it points out is missing. But unfortunately, the GHC API [doesn't expose any of this functionality](https://hackage.haskell.org/package/ghc-8.10.2/docs/GHC-HsToCore-PmCheck.html) --- it builds up interesting structures, and then immediately turns them into error messages.

The wrong way to implement this would be to write something hacky. Theoretically, it should be possible to just figure out which top-level constructors are missing, but there are always going to be quirky edge cases, like "what happens if there is a view pattern?"

I'm not sure how to proceed here.

**Comment by jneira** [comment]
patching ghc? 😝
I am half joking, but maybe an issue in the ghc gitlab repo could be a start

**Comment by isovector** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/19716
