### ISSUE TITLE
Make sure all paths to config files are made absolute

### ISSUE THREAD

**Issue by anka-213** [haskell/haskell-language-server#1895]
This causes test failures when using the latest version of `lsp`

See this PR for a demonstration of the test failures: https://github.com/haskell/haskell-language-server/pull/1894

> > A git bisect points me to this PR: https://github.com/haskell/lsp/pull/326
>
> Lsp changing the current directory was causing other problems and had to be removed. It's unfortunate that this is blocking the 9.0 upgrade, but it will need to be fixed on the hls plugins side. **It should be a simple matter of making sure all relative paths to config files are made absolute using the workspace root**

_Originally posted by @pepeiborra in https://github.com/haskell/haskell-language-server/issues/1649#issuecomment-855247288_

**Comment by pepeiborra** [comment]
Most of the test failures in #1649 are actually caused by test expectations that include file paths:
* All the tests in `tests/functional/Progress.hs` match for progress messages that include a file path
* The code action tests match for diagnostics on a file path
Those tests need fixing, I can send a PR tomorrow if you don't get there first.


The only remaining failure is for the test that checks that the hlint plugin honors the `.hlint.yaml` file, which will probably require changes in the hlint plugin itself

**Comment by pepeiborra** [comment]
The code action tests are failing because they use a direct cradle with relative paths in it. This is a valid thing to do and in order to support it, we'll need to change the working directory to the cradle location in ghcide since lsp no longer does this implicitly.

**Comment by anka-213** [comment]
I believe this has been fixed by @pepeiborra in https://github.com/haskell/haskell-language-server/pull/1897.
