### ISSUE TITLE
Wrong module name suggestions when using a bios cradle

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#1903]
* Extracted from #1901, [reported by @chris-martin ](https://github.com/haskell/haskell-language-server/issues/1901#issuecomment-857064054)
* Cradle output:

```
-ihaskell/typeclasses/src
-XApplicativeDo
-XBlockArguments
-XDeriveFunctor
[...]
Typeclasses.Postgres.Querying
Typeclasses.Postgres.Connection.PoolSetup
Typeclasses.Postgres.Connection.Secrets
[...]
```

* Wrong recommendation:

![Screenshot from 2021-06-08 13-48-00](https://user-images.githubusercontent.com/399718/121248358-952b7180-c860-11eb-9f66-3696f3e52589.png)

/cc @tittoassini (plugin author)

**Comment by chris-martin** [comment]
I've also tried modifying my cradle to output paths instead, and I still get the same result.

**Comment by jneira** [comment]
Yeah it seems it is picking the workspace root dir (where the hie.yaml lives?) instead `${workspace_root}/haskell/typeclasses/src` as base dir to produce suggestions

**Comment by cdsmith** [comment]
There are two problems here, one with haskell-language-server, and one with the test case:

1. The problem with the test case is that it doesn't clear the import paths, so `.` is still in there.  You can fix this by passing just `-i` followed by `-ihaskell/typeclasses/src`.  The first argument clear the list of import paths to remove `.`
2. The problem with haskell-language-server is that the module name plugin misbehaves when one source path is nested inside of another.  It should really check whether the module name is correct relative to any of the import paths, rather than stopping at the first one.

**Comment by cdsmith** [comment]
I'm working on a PR for this.
