### ISSUE TITLE
CI job to ensure flake works

### ISSUE THREAD

**Issue by teto** [haskell/haskell-language-server#2026]
Right now (on c78363fcf6ff690cd13cc8b4ef0e8154cd814ab7 ) the flake doesn't build because of  : 
```
haskell-language-server on  master 
➜ nix build
note: keeping build directory '/tmp/nix-build-ghcide-1.4.0.3.drv-2'
error: builder for '/nix/store/67syxhr6zablyh11gnfsysm3jy2mqjy1-ghcide-1.4.0.3.drv' failed with exit code 1;
       last 10 log lines:
       >   $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.1.0:Distribution.Simple.Configure
       >   configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.1.0:Distribution.Simple.Configure
       >   configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.1.0:Distribution.Simple
       >   confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.1.0:Distribution.Simple.UserHooks
       >   configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.1.0:Distribution.Simple
       >   defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.1.0:Distribution.Simple
       >   defaultMain, called at /nix/store/4mdp8nhyfddh7bllbi7xszz7k9955n79-Setup.hs:2:8 in main:Main
       > Setup: Encountered missing or private dependencies:
       > implicit-hie-cradle >=0.3.0.5 && <0.4
       >
       For full logs, run 'nix log /nix/store/67syxhr6zablyh11gnfsysm3jy2mqjy1-ghcide-1.4.0.3.drv'.
```
Would be nice to prevent changes that break it or mark it as broken. There seems to be a CI job for it but it was skipped on the PRs I've looked at.

**Comment by berberman** [comment]
The current behaviour is somewhat intended:
https://github.com/haskell/haskell-language-server/blob/78381b8135811618101a9177ffd32102dac56b68/.github/workflows/nix.yml#L63-L66

The status of job `Nix/build` is not required for merging a PR. Why? For a PR that updates one dependency, e.g. https://github.com/haskell/haskell-language-server/pull/2020, the contributor needs update:

1. package description (.cabal) file
2. cabal project (.project) file
3. stack hpack files for each GHC version we have

since we are maintaining multiple installation methods. Every Haskell programmer should know `cabal-install` and `stack` imo, because they are kind of "standard" build tools. However, it would be too annoying to let non-nix users cope with nix specified issues. Maintaining each distribution way requires lots of efforts, so I think nix flake here is a less important bonus, compared with `cabal-install` and `stack`, and should never block the merge of PRs. Contributions like https://github.com/haskell/haskell-language-server/pull/2030 are always welcome.

**Comment by teto** [comment]
I get it, the flake is nice to have but not central to development :+1:
Thanks for the answer.

I wonder if there could be a nix service that keeps that last revision that worked for the flake. like git bisect but for to find the last revision that flake.nix succeeded to build (pipedream).
