### ISSUE TITLE
Dynamic linking does not work on Windows

### ISSUE THREAD

**Issue by Tarmean** [haskell/haskell-language-server#2048]
I'm usually compiling haskell-language-server on Windows 10 with stack. Running `stack build` to build 8.10.4 on commit 45fdb257 or later results in compiler errors like:

```
hie-compat                       > src-ghc810\Compat\HieAst.hs:20:8: error:
hie-compat                       >     Could not find module `Prelude'
hie-compat                       >     Perhaps you haven't installed the "dyn" libraries for package `base-4.14.1.0'?
hie-compat                       >     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
hie-compat                       >    |
hie-compat                       > 20 | module Compat.HieAst ( mkHieFile, enrichHie ) where
```
From looking at the issue tracker it seems that dynamic linking doesn't work on Windows, but instead of silently being ignored it seems to break the build - at least on the GHC 8.10.4 version installed by stack.
There seems to be some related discussion here? https://github.com/haskell/haskell-ide-engine/issues/1171#issuecomment-482110766

Removing the 

  $targets:
      - --enable-executable-dynamic

line from the respective stack.yaml fixes the build.

**Comment by jneira** [comment]
Hi, thanks for the bug report. We are restoring static linking again with #2044, as there were problems related in linux and the reason to enable it does not hold. You can remove the config that enables it from the stack yaml you are using if you dont want to wait on the pr merge.
I assumed incorrectly that dynamic linking [was a no op in windows but it is not the case](https://github.com/haskell/haskell-language-server/pull/2031#issuecomment-885440181). The problem here is the ghc distributed for windows (and the bootstrap libs it includes like base) is not prepared for dynamic linking.
Sorry for the inconveniences!

**Comment by Tarmean** [comment]
Wow, a fix time of -5 hours is very impressive. Thank you for your amazing work!
