### ISSUE TITLE
Wingman produces invalid code due to missing qualifiers when ADT is in a different module

### ISSUE THREAD

**Issue by nmichael44** [haskell/haskell-language-server#2564]
### Your environment

Which OS do you use: Ubuntu

Which LSP client (editor/plugin) do you use:
VSCode with Haskell Language Support version 1.8.0

Describe your project (alternative: link to the project): stack.yaml

### Steps to reproduce
Two modules: E.hs
```
module E (
  Oper(..)
  , Exp(..)) where

data Oper = And | Or | F1 | F2
  deriving (Eq, Show)

data Exp =
  Lit Bool
  | FunCall Oper [Exp]
  | Var String
  deriving Eq
```
and Bug.hs
```
{-# LANGUAGE LambdaCase #-}
module Bug ()
where

import qualified E

foo :: E.Exp -> E.Exp
foo = \case   Lit b -> _
  FunCall op exps -> _
  Var s -> _
```
when `foo = \case` is typed wingman suggests to complete-case-constructors.  But as you can see above they are filled in but without any qualification (`Lit` instead of `E.Lit`) resulting in an invalid program.

### Expected behaviour
The correct qualification should be produced.

### Actual behaviour
No qualification is used resulting in an invalid program.

**Comment by jneira** [comment]
thanks for the bug report 
//cc @isovector

**Comment by isovector** [comment]
Wingman is presently on the backburner, and I'm not going to have a chance to work on this for quite a while. But the solution here is to change this line:

https://github.com/haskell/haskell-language-server/blob/7c9b9327d83261a6d40e54a4a2078667f0ddc7bd/plugins/hls-tactics-plugin/src/Wingman/CodeGen.hs#L141

so that it doesn't produce an `Unqual`. How to get what it's qualified as is a mystery to me though.
