### ISSUE TITLE
Include keybindings for common clients in documentation

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-language-server#2613]
See e.g. https://github.com/haskell/haskell-language-server/pull/2603#issuecomment-1016915157

This would make things more user-friendly, but it has a few issues:
- Lots of clients: which ones are we going to include docs for?
    - Even worse: emacs alone has two LSP packages, and those only provide the *functions*, the keybindings are to some degree up to users, and common emacs distributions pick different ones!
- "Wrong" dependency: we then depend on the clients; if they change the keybindings our docs will be out of date, etc.

**Comment by nartamonov** [comment]
> * Lots of clients: which ones are we going to include docs for?

I think the least experienced users benefit the most from the documentation. I have no statistics, but it is reasonable to expect such users to use VSCode. Newcomers and Haskell learners, as well as those who migrate from other languages, are unlikely to use Emacs or Vim immediately. They’ll choose a more familiar environment. Those who use Emacs and Vim have more ability (because of their experience, first of all) to understand how their editor interacts with HLS, event without comprehensive docs.

Of course, I’m not saying that documentation for other editors is less important (*it's not!*), but I’m sure it’s better to start with VSCode. Disclaimer: I'm on the side of Haskell learners so I can be biased 😃

**Comment by michaelpj** [comment]
Nobody has asked for this in a long time, and I think the arguments for it being a bad idea are compelling.
