### ISSUE TITLE
Enable the rename plugin on single component projects 

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#2804]
Currently the rename plugin is disabled (and hence, not linked to the distributed binary) because it doesn't work reliably on multi-component projects (this is not the plugin's fault, but rather HLS / hie-bios). 

While there is work being done to address this, it's been almost a year since the plugin was contributed, and we regularly get requests for the functionality. So it would be nice to enable the plugin at least in single component projects.

**Comment by OliverMadine** [comment]
I think this is reasonable. The issue is that it currently partially performs renames for multi-component projects. If we enable it for single component projects, I think we need either:
1. a good way of letting the user know of this limitation (maybe in settings when they enable it).
2. to restrict the renames to a single component (to stop partial behaviour).
3. to block renaming entirely if the user is working within a multi-component project (do we have reliable way of knowing this?)

**Comment by michaelpj** [comment]
Yeah, I think if we could just fail informatively in the unsupported setting, that might be fine.

**Comment by michaelpj** [comment]
Although, to be clear, a package with a test suite is a "multi-component project", right? So would this in practice rule out essentially all users?

**Comment by OliverMadine** [comment]
> Although, to be clear, a package with a test suite is a "multi-component project", right? So would this in practice rule out essentially all users?

Yes, I think the second option that I listed would be the preferred behaviour then?

In the case of a package with a test suite, we would perform the rename within the single-component (i.e. excluding the test suite). We could also warn the user that the rename was only performed across one component (if they are in a multi-component project).
