### ISSUE TITLE
Data type reachability from within another data type

### ISSUE THREAD

**Issue by eyeinsky** [haskell/haskell-language-server#3066]
Not sure if this is something that is in scope for HLS at all, but here goes:

Could there a way to query if one data type is reachable from another? E.g given data `A = A1 [B] | A2 B (Maybe C)` we know that `B` is always reachable from `A` (because it exists in both branches), while `Maybe a` and `C` may be reachable (i.e, they are if a value is the `A2` branch and not if it's the `A1` branch).

This feature is valuable if there are deep type hierarchies and you wonder if some type is somewhere within another type at all.

**Comment by Ailrun** [comment]
Could you elaborate more about what you mean by "reachability"?
I'm a bit confused with your example, since, because of the list type, `B` should be the "may be reachable" case as well if you care each constructor in a sum type (i.e. because of list type).

**Comment by michaelpj** [comment]
I think this is *probably* out of scope, since we are primarily a LSP server, and fitting this kind of somewhat-arbitrary query and response setup into LSP is a real pain. Maybe it could somehow be jammed into the new type hierarchy feature in 3.17?

Regardless, I think the most promising path forwards would be a standalone implementation built on hiedb, which would then be fairly easy to bring into HLS if we could figure out how the interaction should work.

**Comment by eyeinsky** [comment]
ACK for out of scope.

> type hierarchy feature in 3.17

What is this referring to? (LSP latest release seems to be 1.7.0.0, surely not version 3.17 of it?)

For @Ailrun question: for me, the type level presence was what I meant, that is: if I were looking for `B` then can it be in the data type `A` at all? This helps with large and unfamiliar data type hierarchies, or large ASTs (e.g template haskell) where it's sometimes difficult to tell what contains what.

**Comment by michaelpj** [comment]
Version 3.17 of the LSP specification.

**Comment by michaelpj** [comment]
Tentatively closing as out of scope
