### ISSUE TITLE
GADT syntax converter throws out all datatype comments

### ISSUE THREAD

**Issue by uhbif19** [haskell/haskell-language-server#3516]
### Your environment

haskell-language-server version: 1.8.0.0 (GHC: 8.10.7)

VS Code

### Steps to reproduce

Run rewrite to GADT action on:

```
data AuctionTerms = AuctionTerms
  { -- | What is being sold at the auction?
    auctionLot :: !AssetClass
  }
```

### Expected behaviour

Got:

```
data AuctionTerms where
  AuctionTerms :: {
     -- | What is being sold at the auction?
     auctionLot :: !AssetClass
  } -> AuctionTerms
```

### Actual behaviour

Got:

```
data AuctionTerms where
  AuctionTerms :: {auctionLot :: !AssetClass} -> AuctionTerms
```

**Comment by July541** [comment]
It's a [known](https://github.com/haskell/haskell-language-server/tree/master/plugins/hls-gadt-plugin#known-limitations) limitation because dealing with comment much harder for me.

Any improvements are welcomed!

**Comment by uhbif19** [comment]
@July541 Could you point to any relevant parts of code or issues? Like are there any parts of HLS which do handle comments?

**Comment by July541** [comment]
Sure.

https://github.com/haskell/haskell-language-server/pull/2899#issuecomment-1126727324 and https://github.com/haskell/haskell-language-server/pull/2899#issuecomment-1127813087 and https://github.com/haskell/haskell-language-server/pull/2899#issuecomment-1130144103 are some discussion described the pain while dealing with comment.

For code details, https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-gadt-plugin/src/Ide/Plugin/GHC.hs#L88 used to convert data declarations to GADT syntax, all comments are dropped here.

While stepping in these codes, you may find the differences between different versions of `ghc-exactprint`, and another problem is how to identify the comments, comments can be attached to several elements.

> Like are there any parts of HLS which do handle comments?

- ghcide has a simple handwritten parser to parse comments for top level definition, this is not what we want.
- `hls-tactics-plugin` has some module to work with `ghc-exactprint`, not sure if there is something about comments, but it doesn't work with ghc9.2+.
- `hls-haddock-comment-plugin` attach comments to function, but it is used to add comments instead of reading comments.

**Comment by uhbif19** [comment]
Thanks for references! 

I also have comment duplicating bug with "Add import" refactoring, so that is probably related to ghcides "simple handwritten parser" too.

**Comment by July541** [comment]
> I also have comment duplicating bug with "Add import" refactoring

Do we have a related issue?

**Comment by uhbif19** [comment]
@July541 I could not find anything matching it. I can create new.
