### ISSUE TITLE
HLS Completion Scope

### ISSUE THREAD

**Issue by feedseed** [haskell/haskell-language-server#3798]
## Description

Howdy, I was wondering whether it is possible to restrict the scope of completion items to the current scope/namespace of the file/project one is currently working in. Whenever I work on a project, an unhinged list of completions is presented to me, consisting of all functions that are defined somewhere in the modules I have installed. Unfortunately, I just want to see the stuff I have imported, not every other library I am not using that makes completion completely useless. Also, is there no way to assign a priority to a completion? 

Doesn't work in project mode, nor single file mode.

I tried to find some information on this subject, but until now, I couldn't get it to work.

## Environment

Void Linux, Installed Haskell tool chain using GHCup, neovim with LSPconfig.

**Comment by fendor** [comment]
Potentially related to #3646 

However, we try to avoid too many config options since they are one additional code path to test and maintain.

Perhaps we can simply sort the completions better, coming up with better heuristics to decide the order. The order of the completions is lsp-client dependent, iirc, but we can supply a custom comparison string https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion

**Comment by michaelpj** [comment]
I'm pretty sure we already sort the completions and use the comparison string so that local completions are first :thinking:

**Comment by fendor** [comment]
> not every other library

Library your project depends on? Or in the case of single Haskell files, GHC boot libraries?

This bug report sounds a little bit unclear, can you perhaps provide an example of what's going on?

**Comment by michaelpj** [comment]
Never got a reply here, so closing
