### ISSUE TITLE
The formatting notification is too distracting 

### ISSUE THREAD

**Issue by banacorn** [haskell/haskell-language-server#381]
I think there's really nothing worth notifying when formatting the document, especially when the formatting command has to be triggered by user by default. It becomes even more distracting when you enable, say, `format on save`.

<img width="584" alt="截圖 2020-09-07 下午2 22 29" src="https://user-images.githubusercontent.com/797844/92354890-bdd9db80-f115-11ea-9b4b-f05707e5f2ab.png">

There should be an option in the settings for disabling these notifications.

**Comment by bubba** [comment]
I noticed this as well, formatting doesn't usually seem to be that time intensive of an operation so it would make sense to debounce it first.

**Comment by pepeiborra** [comment]
Formatting can block for other reasons though, like consulting a cradle. Debouncing is always good, even better if done on the LSP client side since it is a crosscutting concern across all progress notifications.

**Comment by georgefst** [comment]
Worth noting, currently the progress notification only shows for Ormolu/Fourmolu, presumably because the others aren't calling [withIndefiniteProgress](https://hackage.haskell.org/package/haskell-lsp-0.22.0.0/docs/Language-Haskell-LSP-Core.html#t:LspFuncs).

The notification doesn't annoy me *per se*, but what's odd is that it hangs around for almost a second after formatting appears to have finished, even on a trivial file. This could be because we call Ormolu with the idempotency check, which means that everything is actually formatted twice, but it's longer than I'd expect even accounting for that. Anyway, having a threshold of even a second would make this a non-issue for me.

**Comment by jneira** [comment]
I am gonna use `withIndefiniteProgress` in the hlint plugin, so this would affect it

**Comment by Profpatsch** [comment]
I get the problem that with `format-on-save`, formatting will block saving the file when hls is working on something in the background (especially when it crashes/hangs, which happens if the file has syntax errors on hls start for example).

Requiring me to manually stop hls and interrupt the formatting before I can save the file.

**Comment by michaelpj** [comment]
Should be fixed now, we will only get a progress notification if it takes some time.
