### ISSUE TITLE
Can't resolve cabal test suite dependencies with multiple test suites

### ISSUE THREAD

**Issue by Softsun2** [haskell/haskell-language-server#4085]
### Your environment

Which OS do you use?
MacOS

Which version of GHC do you use and how did you install it?
9.2.8 from nixpkgs (23.05)

How is your project built?
cabal (dependencies provided by nix). my [flake.nix](https://github.com/Softsun2/lumea/blob/hls-issue/flake.nix)

Which LSP client (editor/plugin) do you use?
Neovim+LanguageClient-neovim (builtin client)

Which version of HLS do you use and how did you install it?
1.10.0.0 from nixpkgs (23.05)

Have you configured HLS in any way (especially: a `hie.yaml` file)?
No (unless passing the logfile flag counts)

### Steps to reproduce
1. Configure cabal project with multiple test suites. Here's my [exact cabal file](https://github.com/Softsun2/lumea/blob/hls-issue/lumea.cabal).
2. Configure test suite with dependencies:
```cabal
-- lumea.cabal
...
test-suite meta-test
    type: exitcode-stdio-1.0
    main-is: MetaTest.hs
    build-depends:
        base ^>=4.16.4.0,
        HUnit,
        pandoc, pandoc-types,
        Lumea,
        filepath, directory
    hs-source-dirs: test
    default-language: Haskell2010
...
```
4. Import dependencies in configured test file:
```haskell
-- test/MetaTest.hs
module Main where

import qualified Meta
import Test.HUnit
import Text.Pandoc
...
```
6. Observe that running test suite resolves the imported dependencies and runs fine (running `cabal test meta-test`)
7. Edit test file, observe dependency can not be resolved:
<img width="851" alt="Screenshot 2024-02-18 at 7 18 59 PM" src="https://github.com/haskell/haskell-language-server/assets/87036649/53f5dc70-6305-4ec3-ac19-758c7a7ffb2a">

### Expected behaviour

I'd expect hls to be able to resolve the pandoc dependencies when editing my test file if they can be compiled and run.

### Debug information

Curiously, if I add pandoc as a dependency to another test suite. A test suite with the same `hs-source-dirs`, then when I'm editing `test/MetaTest.hs` the dependency is resolved and I don't get a warning.

```cabal
test-suite site-test
    type: exitcode-stdio-1.0
    main-is: SiteTest.hs
    build-depends:
        base ^>=4.16.4.0,
        HUnit,
        pandoc, pandoc-types,
        Lumea,
        filepath, directory
    hs-source-dirs: test
    default-language: Haskell2010

test-suite meta-test
    type: exitcode-stdio-1.0
    main-is: MetaTest.hs
    build-depends:
        base ^>=4.16.4.0,
        HUnit,
        pandoc, pandoc-types,
        Lumea,
        filepath, directory
    hs-source-dirs: test
    default-language: Haskell2010
```
Nothing looks out of the ordinary in the logs. I can provide them if requested.

**Comment by fendor** [comment]
Hi, thank you for the bug report!

This looks like an issue with the implicit project discovery mechanism of HLS which usually messes up when components (e.g. the testsuites) overlap.
To fix this for your example, create a `hie.yaml` file with the contents:
```yaml
cradle:
  cabal:
```
in the root of your project.

**Comment by Softsun2** [comment]
Thanks for your response. Not knowing much about the problem this solution isn't very intuitive. It works but I don't understand why. Could you give me a brief explanation or point me to a reference?

**Comment by fendor** [comment]
In short, a `hie.yaml` tells HLS which file paths belong to which component (component being a cabal test suite, library, executable, etc...). We always have one, either written by the user or generated at run-time.

By default, HLS uses a discovery mechanism to map file paths (such as `test/`) to a component (e.g. `test:meta-test`).
It does that by looking at the `hs-source-dirs` of each component. It is simply a bug that HLS doesn't generate more specifically `test/Metatest.hs` maps to `test:meta-test` and `test/SiteTest.hs` belongs to `test:site-test`.

The `hie.yaml` I gave you is the so-called `simple cabal` cradle, which essentially says, don't map file paths to components, but let cabal figure it out on its own. In a nutshell, it calls `cabal repl <name-of-the-file>` and that works out perfectly if you have a recent enough cabal version (newer than 3.2 iirc).

Since the simple cabal cradle is better in almost all situation, the latest HLS release 2.6 also changes the default, so you shouldn't need to write out `hie.yaml` file. 

Closing this, as this is resolved in the latest release, but feel free to ask follow up questions!
