### ISSUE TITLE
Substitute minimal imports / add explicit exports

### ISSUE THREAD

**Issue by jrp2014** [haskell/haskell-language-server#56]
GHC has a `-ddump-minimal-imports` flag. Would it be possible to use the `haskell-language-server` apparatus to write a new app to apply the minimal imports (optionally ignoring Prelude, perhaps) generated automatically?  And across a whole project, rather than file by files in the editor?

For bonus points, it should also be possible to use the set of minimal imports across a project to add explicit export lists to each module derived using the minimal import lists.

Of course, `weeder` does some of this at the module level, but not the module contents level.

Presumably, this would help faster compilation and provide GHC with better optimization opportunities, as well as using the compiler to "annotate" existing code. and make more explicit what the compiler is seeing / deriving.

Undoubtedly the automatically-generated results would need hand tweaking, but I think that it might be a great help to some older code bases that have developed a certain amount of cruft that this sort of analysis could help improve. Doing it by hand, with a shell script or two would be one approach, but it would be good to have something a bit more robust (eg, preserving comments).

Perhaps someone has already done this or it could provide a good demo plugin project for `haskell-language-server`.

**Comment by fendor** [comment]
This feature will require usage of the GHC API: https://hackage.haskell.org/package/ghc-8.6.5/docs/RnNames.html#v:getMinimalImports

I think this issue is a challenge for new contributors but doable.
For the implementation, there are multiple steps that at least I have identified:
* Obtaining a module (e.g. a [parsed module](https://hackage.haskell.org/package/ghc-8.10.1/docs/GHC.html#t:ParsedModule) or even a [typechecked module](https://hackage.haskell.org/package/ghc-8.10.1/docs/GHC.html#t:TypecheckedModule))
  * should be obtained via rules, example given https://github.com/haskell/haskell-language-server/blob/master/src/Ide/Plugin/Ormolu.hs#L53
* Entering somehow the [RenameMonad](https://hackage.haskell.org/package/ghc-8.10.1/docs/TcRnTypes.html#t:RnM)
* Finding a suitable place to implement it (plugin)
* Thinking about the UX (I think a code-lens in the first line suggesting to minimise the imports could be nice)

**Comment by jrp2014** [comment]
Thanks.  In the end, I had a go at implementing this as a ghc plugin:  https://github.com/jrp2014/smuggler2/tree/master/src/Smuggler2

I suspect that making a variant of that plugin for haskell-language-server would be doable, but not offer sufficient advantages to running it via ghc flags to make it worth doing.  The effort might be better spent on providing a more general interface for switching between different sets of ghc flags to allow plugins, etc, to be switched on and off more easily, perhaps on a per module basis, than editing config files.  Perhaps that already exists.  What do you think?

**Comment by pepeiborra** [comment]
I have implemented this as a code lens in #310
