### ISSUE TITLE
CodeLens provided by ModuleName does not disappear properly

### ISSUE THREAD

**Issue by berberman** [haskell/haskell-language-server#564]
### Subject of the issue

![Peek 2020-11-02 18-57](https://user-images.githubusercontent.com/26041945/97860905-e4934780-1d3d-11eb-833b-319d40dac30a.gif)

### Your environment
```
haskell-language-server version: 0.5.1.0 (GHC: 8.10.2) (PATH: /home/berberman/.cabal/store/ghc-8.10.2/haskell-language-server-0.5.1.0-e719e6f687739d6ff770e7a1372b2b19718f9811d322d8cde279a5f71726b6a0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.5.1
ghc:		8.10.2
```

### Steps to reproduce
Just by creating a new file

**Comment by berberman** [comment]
I think this was because vscode didn't save the file after inserting the module name.

**Comment by jneira** [comment]
@berberman thanks for the report, the plugin code lens should be reloaded on not saved edits too //cc @tittoassini

**Comment by tittoassini** [comment]
The way I understand it is the plugin can update the CodeLens (and therefore it will disappear if it is not required anymore) only when is called again by the client. This might take a while and that's why a CodeLens can be left hanging for a while and be applied more than once if one is quick enough at clicking on it :-)

@berberman what did you use to create that nice demo?

**Comment by berberman** [comment]
@tittoassini Oh I see. This should be what we expected:

![a](https://user-images.githubusercontent.com/26041945/98062090-465fc880-1e88-11eb-8f6d-af9f9e325a04.gif)

Well, sometimes it takes too long to disappear. Even in my first gif, it seemd to not disappear at all. My editor is vscode, and I use peek to record my screen.

**Comment by jneira** [comment]
@tittoassini maybe the plugin could check if the module header has been added and being idempotent
