### ISSUE TITLE
Test against ci precompiled binaries

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#595]
* With the lastest releases we can observe that several bugs affecting final users are related with the fact we are offering precompiled binaries and using them by default in the extension/ghcup
* hls developers and ci are testing a version built from source in the same machine so the test suite is green for those bugs
* imo we should run the test suite against the precompiled binaries before make a release, ideally in ci but, at least, locally
//cc @bubba @alanz

**Comment by jneira** [comment]
The environment where run that test suite should be a clean one, different from the ci (for example putting ghc in a non standard location and so on)

**Comment by pepeiborra** [comment]
Big thumbs up, this is a must have

**Comment by bubba** [comment]
I think I have a branch for this: https://github.com/haskell/haskell-language-server/compare/master...bubba:static-binary-tests
Could be dusted off! It worked by downloading the build artefacts from the previous stage and then running the tests against that. The main change needed to the testsuite was the HLS_TEST_EXE env var so that we could point it to the binary

**Comment by jneira** [comment]
From https://github.com/haskell/haskell-language-server/issues/2281#issuecomment-973013466 and https://github.com/haskell/haskell-language-server/issues/2281#issuecomment-973035786

This could have helped to catch the bug about hs-boot files before releasing 1.5.0

In addition to @bubba suggestion another fuzzy test could be run hls in the cli for some real world projects. The obvious one is hls itlsef as it should be fast cause we have all dependencies in cache. We could choose some other projects known to be problematic.

//cc @pepeiborra
