### ISSUE TITLE
Is it possible for go-to-definition to go to the .hs file rather than the hs-boot file?

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-language-server#608]
From GHC's point of view, the hs-boot file is correct, but it's a little less useful for the user wanting to see a definition!

**Comment by jneira** [comment]
@expipiplus1  is it still happen with newer hls versions?

**Comment by expipiplus1** [comment]
This is all fixed in current versions. 

This is a neat thing:

- If I "go to definition" in a file which hasn't used a `SOURCE` import then I as expected go to the `.hs` file
- If I "go to definition" in a file which imports the identifier via `SOURCE` then I get a choice about where to jump to!
- I get the same choice when I "go to definition" in the `.hs-boot` file itself.

Very nice!

**Comment by wz1000** [comment]
> If I "go to definition" in a file which hasn't used a SOURCE import then I as expected go to the .hs file

Would you like a choice in this scenario also? It is possible, but might make things a bit slower. I didn't implement this because this is the common case and it didn't feel like it made sense to make this slower for questionable benefit.

Right now the implementation is a bit of a hack: we first check the definition that GHC reports for a given name. If that is not a boot file, we just return it. Otherwise, we look up the definition in the database, which should have both the boot file and the source file.

**Comment by expipiplus1** [comment]
I don't think that's necessary, but it might be nice to be able to go to the .hs-boot definition from the corresponding .hs definition I suppose. 

Not something I use often enough to be worth any serious engineering though!!!

**Comment by wz1000** [comment]
> it might be nice to be able to go to the .hs-boot definition from the corresponding .hs definition

You can do that with "find references"!

**Comment by expipiplus1** [comment]
oh yeah! thanks!
