### ISSUE TITLE
Distribute binaries via Homebrew

### ISSUE THREAD

**Issue by ad-si** [haskell/haskell-language-server#703]
It would be cool if I could install hls it with a simple:
```sh
brew install haskell-language-server haskell-language-server-wrapper
```
Here is the documentation on how to add it to Homebrew:
https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by jneira** [comment]
More installation methods supposes to reach more users and that is good. However they should be set up and more importantly, updated. IDeally it should be done in ci automatically.
So we need someone willing to accomplish the task 😄

**Comment by jneira** [comment]
Some investigation has been done by @ELLIOTTCABLE: https://github.com/Homebrew/discussions/discussions/386
Thanks for it!

**Comment by jneira** [comment]
haskell-language-server is on hackage now and can be installed in a more friendly way with cabal install: https://hackage.haskell.org/package/haskell-language-server

**Comment by kret** [comment]
`haskell-language-server` is now available as a Homebrew formula (`brew install haskell-language-server`). This is a version compiled with current GHC from Homebrew (8.10.4). I hope it works 😅 

I guess this is not ideal (single GHC version support), but I think it is a reasonable compromise between Haskellers' needs and Homebrew's rules.

IMO it would be great to distribute the whole release. As I see it we could create a "Haskell tap" similar to this: https://github.com/kret/homebrew-tools, but in an official Haskell repo. There we could distribute binaries without need to strictly conform to Homebrew rules, but at the cost of having to occasionally update it ourselves.
I was thinking about distributing the wrapper and language server binaries per GHC version so that users could pick whatever they need, perhaps also with a single command full release installation. I can prepare such version on my private tap as an example and then it could be moved over to official repo, if accepted as a solution.

**Comment by kret** [comment]
Updated my private tap (https://github.com/kret/homebrew-tools).
It now contains 5 casks:
- `kret/tools/haskell-language-server-full`
- `kret/tools/haskell-language-server-wrapper`
- `kret/tools/haskell-language-server-8104`
- `kret/tools/haskell-language-server-884`
- `kret/tools/haskell-language-server-865`

The `full` contains the full release of course, the rest contains single binaries (8104 - because dots are not allowed in names, hyphens could be there if you think they look better).

You can play around with un/installing and using to verify if that is usable.
All comments are welcome, I can make updates, or you can open PRs of course.

If this becomes satisfactory, we can decide next steps, like:
- moving to an official Haskell/HLS tap,
- which binaries to include like this,
- automating tap refresh upon new release,
- ?

**Comment by jneira** [comment]
@kret wow, that is really really great, many thanks for setup the formula and the alternative packages

I think the next immediate step could be add homebrew as a new install method in the README and make it public (in the next release announce f.e.)

>moving to an official Haskell/HLS tap,

Create a new repo in the org is not a trivial task, maybe we could start to use your repo (or a different under another org, as you consider).

> automating tap refresh upon new release,

that would be nice, what would be the update suppose? changing `.rb` files?

**Comment by jneira** [comment]
> and make it public

https://twitter.com/jneira/status/1371581513041547264

**Comment by kret** [comment]
> @kret wow, that is really really great, many thanks for setup the formula and the alternative packages
I hope it is useful for others 😁 
Thanks for the mention as well 😊 @carlocab - Homebrew maintainer - did most of the work though. Very helpful!

> I think the next immediate step could be add homebrew as a new install method in the README and make it public (in the next release announce f.e.)
I leave that up to you 😇 

> > moving to an official Haskell/HLS tap,
> Create a new repo in the org is not a trivial task, maybe we could start to use your repo (or a different under another org, as you consider).
It can stay in my repo for now, if HLS decides take over, I can help migrate.

> > automating tap refresh upon new release,
> that would be nice, what would be the update suppose? changing `.rb` files?
Yes, basically. I saw AdoptOpenJDK had something like this; we could use it as an inspiration.
https://github.com/AdoptOpenJDK/homebrew-openjdk, see the `/Templates/*.tmpl`, `/auto_updater.sh`, `/.github/workflows/updater.yml`, `/casks.txt`.

**Comment by carlocab** [comment]
>single GHC version support

Formulae that builds the language server for other versions of GHC would be, in my opinion, also acceptable at Homebrew/core. (Of course, this would need to be acceptable to other maintainers too.)

**Comment by kret** [comment]
That would be great, @carlocab :)
Is there a way to ask Homebrew maintainers if they would accept such an approach before creating the formulae?

As to the _how_ I would need help with getting the correct way to provide GHC versions for compilation:
* Is there a way to tell Cabal to fetch specific GHC for compilation?
* I see that there are `ghc@8.6` (8.6.5), `ghc@8.8` (8.8.4) and `ghc` (8.10.4) versions in Homebrew. Does it mean I should add the specific versions HLS needs as new formulae (like ghc@8.6.4, ghc@8.10.3 etc)? ...and then use these to build HLS formulae? That does not sound super exciting...

**Comment by jneira** [comment]
> I see that there are ghc@8.6 (8.6.5), ghc@8.8 (8.8.4) and ghc (8.10.4) versions in Homebrew. Does it mean I should add the specific versions HLS needs as new formulae (like ghc@8.6.4, ghc@8.10.3 etc)? ...and then use these to build HLS formulae? That does not sound super exciting...

Imho i think that to have the last minor versions usually is enough for most users (if everything goes well and the last minor version is not worse than the previous one, but then the ghc formula should not be update neither)

**Comment by carlocab** [comment]
> Is there a way to ask Homebrew maintainers if they would accept such an approach before creating the formulae?

Not currently, no. Might be best to start with a pull request for a language server for `ghc@9`.

**Comment by kret** [comment]
Ok. So based on your inputs, I will try to provide the new formulae for the Homebrew-provided GHC versions (so 8.6 and 8.8).
Concerning GHC 9 - I don't see HLS binary for that version in 1.0.0 release. I assume that it means that it is not yet supported by HLS, correct?

Hmm, so in order to provide several HLS binaries as formulae I have to separate the wrapper binary out, and make language server binaries `depends_on "haskell-language-server-wrapper"`. Is my understanding correct, that wrapper can be compiled with any GHC version to work with all language server binaries?

Following that, is there a way to tell Cabal to _not_ compile language server binary when executing `v2-install exe:haskell-language-server-wrapper`? ...I now do this:
```ruby
system "cabal", "v2-install", *std_cabal_v2_args
rm bin/"haskell-language-server"
```

**Comment by kret** [comment]
Concerning https://github.com/Homebrew/homebrew-core/pull/73522...
@carlocab, I think wrapper is necessary, it serves as an entry point to HLS for IDEs: users point an IDE to wrapper and it dispatches to appropriate language server binary based on the project's configuration. @jneira, correct me if I am not correct please.

**Comment by carlocab** [comment]
So how does someone use the existing `haskell-language-server` formula without it?

**Comment by kret** [comment]
My understanding is that if one only has a single Haskell project then they might use the appropriate binary directly. As soon as they have another Haskell project that uses a different GHC version they would need to use wrapper and two dedicated language server binaries. That way an IDE can be pointed to the wrapper and both projects can be worked on in same IDE.

**Comment by carlocab** [comment]
Can the other language servers just use the wrapper that comes with the existing `haskell-language-server` formula? It already ships one anyway, and you're essentially building the same thing twice across two different formulae. Not to mention the added difficulty of keeping the two versions in sync.

**Comment by jneira** [comment]
@kret you are right in all your comment above 😄 

> Is my understanding correct, that wrapper can be compiled with any GHC version to work with all language server binaries?

Yeah, it can be bult with all supported ghc versions and it works at runtime choosing the right hls-{version} for all supported ghc versions

> Following that, is there a way to tell Cabal to not compile language server binary when executing v2-install exe:haskell-language-server-wrapper? ...I now do this:

That command should install only hls-wrapper, and it does when installing hls from hackage:

```
PS D:\dev\ws\haskell> cabal install haskell-language-server:haskell-language-server-wrapper --installdir test
Resolving dependencies...
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
.......
 - ghcide-0.7.3.0 (lib) (requires download & build)
 - haskell-language-server-0.9.0.0 (lib) (requires download & build)
 - haskell-language-server-0.9.0.0 (exe:haskell-language-server-wrapper) (requires download & build)
 ```

But it builds all executables if you run the command in the repo, i would say it is a cabal bug but it seems your workaround is needed

```
PS D:\hls> cabal install exe:haskell-language-server-wrapper
....
 - haskell-language-server-1.0.0.0 (lib) (requires build)
 - haskell-language-server-1.0.0.0 (exe:haskell-language-server) (requires build)
 - haskell-language-server-1.0.0.0 (exe:haskell-language-server-wrapper) (requires build)
 ```

**Comment by kret** [comment]
Updated `haskell-language-server` formula to also include HLS binaries compiled for GHCs 8.6 and 8.8.
Again with great help from @carlocab :)

**Comment by jneira** [comment]
Many thanks all to open a new path to install hls :smiley_cat: 
I think only we would need update README.md install section with homebrew.
