### ISSUE TITLE
Update links to issues in ghcide tests

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#718]
* ghcide tests are linked to ghcide repo issues and they will be transferred or closed
* so we should update them in the source file
* for example

https://github.com/haskell/haskell-language-server/blob/d4f5d436641efdca15f68f1d435901b5057e351d/ghcide/test/exe/Main.hs#L2517-L2518

**Comment by peterwicksstringfield** [comment]
These are fine I think since they are full links?
```
2650:    [ -- Test for https://github.com/haskell/ghcide/pull/212
2696:    -- Regression test for https://github.com/haskell/ghcide/issues/614
```

I don't see any instances of this sort of thing outside of ghcide/test/exe/Main.hs

And the only instances in ghcide/test/exe/Main.hs occur in 2480..2523. It's just that one block of code.

In
```
2481:  , test  yes    yes    fffL8      fff           "field in record construction     #71"
``` 
that 71 is ghcide issue 71, which is already closed. Since its closed, will it be transferred? What should it be changed to, ("field in record construction ghcide 71")? ("field in record construction https://github.com/haskell/ghcide/issues/71")?

And in
```
2489:  , test  yes    yes    vvL16      vv            "plain parameter"                      -- 120
```
the 120 is ghcide pull 120, which is merged. That also won't be transferred I think? Should it become "-- ghcide 120"? Or "-- https://github.com/haskell/ghcide/pull/120"?

Most of the other numbers are like 71 and 120, either closed issues or merged pulls ... here are the only exceptions:

In
```
2517:  , test  broken broken outL45     outSig        "top-level signature             #310"
```
that 310 is an open ghcide issue that has not yet been transferred. What should this turn into?

And in
```
2491:  , test  yes    yes    opL16      op            "top-level operator"                   -- 120, 123
```
that 123 is ghcide issue 123, which is open, and has been transferred to hls issue 713. So I guess we can change the 123 to "hls 713", or even just "713". Or we could change it to "ghcide 123", because the old issue redirects to the new one.

**Comment by jneira** [comment]
@peterwicksstringfield thanks for take a look at this

> These are fine I think since they are full links?

Well, we are gonna to transfer them all, closed ones included, so ideally we should replace them with the new link (so we have to wait for that). Old links are automatically forwarded to the new issues so no a big deal

>  Since its closed, will it be transferred?
> the 120 is ghcide pull 120, which is merged. That also won't be transferred I think? Should it become "-- ghcide 120"? Or "-- haskell/ghcide#120"?

closed issues will be transferred but pr's won't, so we have to use full links for pr's 

> that 310 is an open ghcide issue that has not yet been transferred. What should this turn into?

In the new issue id when it is transferred (i've just transferred that one and now it is https://github.com/haskell/haskell-language-server/issues/767)

> that 123 is ghcide issue 123, which is open, and has been transferred to hls issue 713. So I guess we can change the 123 to "hls 713", or even just "713". Or we could change it to "ghcide 123", because the old issue redirects to the new one.

I would use #713

**Comment by peterwicksstringfield** [comment]
That answers all my questions. When the rest of the closed issues are transferred I'll put up a PR to fix the numbers and close this issue. Thanks!

**Comment by peterwicksstringfield** [comment]
https://github.com/haskell/haskell-language-server/pull/1142

**Comment by peterwicksstringfield** [comment]
(Is there a reason that https://github.com/haskell/ghcide/issues/104 didn't get moved? Seems weird that there is just 1 issue left back on ghcide.)
