### ISSUE TITLE
Reenable -fghc-lib build

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#784]
The ghc-lib build (using flag `ghc-lib` for the `ghcide` package) needs a test. https://github.com/haskell/haskell-language-server/commit/0db12a71 shows what is missing, but needs adjusting to build only ghcide and nothing else. Probably best to create a separate workflow for it

**Comment by jneira** [comment]
Not sure if we should remove ghc-lib support entirely, does daml still needs it here?
//cc @ndmitchell @cocreature

**Comment by pepeiborra** [comment]
Indeed. `ghc-lib` is not a good fit for ghcide/hls so the only reason to keep it would be daml.

**Comment by ndmitchell** [comment]
CC @martin-drhu-da and @cocreature - do you have value in the ghc-lib target for HLS/Ghcide? If so, we should enable CI. If not, we should delete it. The middle ground is probably not useful for anyone.

**Comment by cocreature** [comment]
We still use ghcide via ghc-lib so in principle yes, there is value for us. However, we haven’t upgraded our ghcide base commit in ages (I think we’re on a commit from march 2013) so at this point, it seems unreasonable to ask you to keep supporting it just because we might upgrade at some point. Even if we do, we can probably maintain the ghc-lib specific changes in our fork. So my suggestion is to drop it even if it slightly pains me to say that. Thanks for keeping it so long!
